### PR TITLE
Renamed WorlData to GlobalData

### LINKED ISSUE #6: rename GetWorlDataAsync to GetGlobalDataAsync
- typo
- global data sounds more intuitive

### PR DESCRIPTION
**Pull request by pujux**
closes #6

### CODE REVIEW

**Review by egbakou — APPROVED** [review]

**Comment by egbakou** [comment]
Thanks for your contribution :)

**Comment by pujux** [comment]
No Problem! Keep up the good work!

**Comment by egbakou** [comment]
@all-contributors please add @puf17640 for code, tests and doc

**Comment by egbakou** [comment]
@all-contributors please add @puf17640 for code, test and doc

**Comment by egbakou** [comment]
@all-contributors please add @puf17640 for code, test and doc

**Comment by egbakou** [comment]
@all-contributors please add @puf17640 for code, test and doc

**Pull request merged**
